site_name: Introduction à l'architecture logicielle
site_url: https://yostane.github.io/cours-archi-logicielle/
repo_url: https://github.com/yostane/cours-archi-logicielle
repo_name: yostane/cours-archi-logicielle
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yostane

nav:
  - index.md
  - Katas d'architecture:
    - katas.md
    - kata-examples.md
  - Sujets de veille:
    - sujets-vrac.md
    - sujets-2324.md
    - Sujets 24-25:
      - 2425/index.md
      - 2425/adr.md
      - 2425/unclebob.md
      - 2425/cloud_vs_onpremise.md
      - 2425/saas.md
      - 2425/oidc.md
      - 2425/kafka.md
      - 2425/kube.md
      - 2425/structurizr.md
  - archi-doc.md
  - Exemples d'exercices / projets:
    - projet.md
    - sujets.md

plugins:
  - search
  - glightbox

theme:
  logo: img/logo.jpg
  favicon: img/logo.jpg
  name: material
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: light green
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: light green

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
